#!/usr/bin/env bash
export PATH="/usr/lib/rstudio-server/bin/quarto/bin:/home/pgaq/.positron-server/bin/693b6d13ba5d61566bec7f5a4a46126eff7bbbe1/bin/remote-cli:/home/pgaq/.local/bin:/home/pgaq/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"

cd ../
quarto render seasonal
cd run_control
